// Problem 2: Even Fibonacci Numbers
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

let currentNum;
let lastNum;
let evenSum;
let tempNum;

function fiboEvenSum(n) {
    currentNum = 2;
    lastNum = 1;
    evenSum = 0;
    tempNum = 0;

    while(currentNum <= n) {
        if (currentNum % 2 === 0) {
            evenSum += currentNum;
        };
        tempNum = lastNum;
        lastNum = currentNum;
        currentNum = currentNum + tempNum;
    }
    return evenSum;
  }
  console.log(fiboEvenSum(1000))